/** 中考词表里 KEW 没有覆盖、需按中小学生口吻补的释义 */
export interface SimpleGloss {
  meaning: string
  englishMeaning: string
  exampleSentence: string
}

function g(meaning: string, englishMeaning: string, exampleSentence: string): SimpleGloss {
  return { meaning, englishMeaning, exampleSentence }
}

export const ZHONGKAO_EXTRA: Record<string, SimpleGloss> = {
  nineteen: g('十九', 'the number 19', 'She is nineteen years old.'),
  very: g('非常', 'in a strong way', 'This cake is very sweet.'),
  bag: g('包', 'a thing you carry books or food in', 'My bag is on the desk.'),
  tuesday: g('星期二', 'the day after Monday', 'We have PE on Tuesday.'),
  grandparent: g('祖父母', 'the mother or father of your parent', 'My grandparent tells me stories.'),
  be: g('是', 'to exist or to equal', 'I want to be a teacher.'),
  america: g('美国', 'the United States', 'He lives in America now.'),
  its: g('它的', 'belonging to it', 'The dog wags its tail.'),
  culture: g('文化', 'the way a group of people live', 'We learn about Chinese culture.'),
  taxi: g('出租车', 'a car you pay to ride in', 'We take a taxi to the station.'),
  dialogue: g('对话', 'a talk between people', 'Read the dialogue in pairs.'),
  recent: g('最近的', 'happening not long ago', 'I saw a recent photo of her.'),
  ten: g('十', 'the number 10', 'I have ten fingers.'),
  blue: g('蓝色的', 'the colour of the sky', 'The sky is blue today.'),
  feeling: g('感觉', 'what you feel inside', 'I have a happy feeling.'),
  at: g('在', 'in a place or time', 'She is at school now.'),
  he: g('他', 'a word for a boy or man', 'He is my brother.'),
  brother: g('兄弟', 'a boy with the same parents', 'My brother plays football.'),
  we: g('我们', 'you and I', 'We go to school together.'),
  yours: g('你的', 'belonging to you', 'This book is yours.'),
  theirs: g('他们的', 'belonging to them', 'The bikes are theirs.'),
  blackboard: g('黑板', 'a dark board to write on in class', 'The teacher writes on the blackboard.'),
  cat: g('猫', 'a small pet that says meow', 'The cat sleeps on the sofa.'),
  coke: g('可乐', 'a sweet brown drink', 'I drink Coke with lunch.'),
  anything: g('任何东西', 'a thing of any kind', 'Do you need anything from the shop?'),
  sometimes: g('有时', 'not always, but at times', 'I sometimes walk to school.'),
  snowy: g('下雪的', 'with a lot of snow', 'It is a snowy day.'),
  officer: g('警官', 'a police or army worker', 'The officer helps the lost child.'),
  fox: g('狐狸', 'a wild animal with a long tail', 'A fox runs in the forest.'),
  centre: g('中心', 'the middle of a place', 'The park is in the city centre.'),
  driver: g('司机', 'a person who drives', 'The bus driver is kind.'),
  retell: g('复述', 'to tell a story again', 'Please retell the story to me.'),
  europe: g('欧洲', 'a large part of the world', 'France is in Europe.'),
  rusia: g('俄罗斯', 'another spelling of Russia', 'Rusia is another spelling of Russia.'),
  nearly: g('几乎', 'almost', 'It is nearly time for lunch.'),
  where: g('哪里', 'in what place', 'Where is my pencil?'),
  june: g('六月', 'the sixth month', 'School ends in June.'),
  seventeen: g('十七', 'the number 17', 'My sister is seventeen.'),
  wednesday: g('星期三', 'the day after Tuesday', 'We have English on Wednesday.'),
  her: g('她的', 'belonging to a girl or woman', 'This is her book.'),
  they: g('他们', 'some people or things', 'They play in the yard.'),
  forty: g('四十', 'the number 40', 'My uncle is forty years old.'),
  mother: g('妈妈', 'your female parent', 'My mother cooks dinner.'),
  tourist: g('游客', 'a person who visits a place', 'The tourist takes photos.'),
  rubbish: g('垃圾', 'things you throw away', 'Put the rubbish in the bin.'),
  box: g('盒子', 'a container with four sides', 'The gifts are in the box.'),
  kilo: g('千克', 'a unit for heavy things', 'I buy one kilo of apples.'),
  glove: g('手套', 'clothes for your hands', 'Wear a glove in the cold.'),
  you: g('你', 'the person I am talking to', 'You are my best friend.'),
  march: g('三月', 'the third month', 'We plant trees in March.'),
  sun: g('太阳', 'the bright star that gives us light', 'The sun is hot in summer.'),
  friday: g('星期五', 'the day after Thursday', 'Friday is before the weekend.'),
  visitor: g('访客', 'a person who comes to see you', 'A visitor knocks on the door.'),
  august: g('八月', 'the eighth month', 'August is a hot month.'),
  anyone: g('任何人', 'any person', 'Anyone can join the game.'),
  here: g('这里', 'in this place', 'Please sit here.'),
  back: g('回来', 'to the place you were before', 'Please come back soon.'),
  prisoner: g('囚犯', 'a person kept in prison', 'The prisoner wants to go home.'),
  english: g('英语的', 'about the English language', 'We have an English class.'),
  vcd: g('影碟', 'a disc with a film on it', 'We watch a VCD at home.'),
  england: g('英格兰', 'a country in the UK', 'London is in England.'),
  eighth: g('第八', 'number 8 in a list', 'She is the eighth in line.'),
  windy: g('有风的', 'with a lot of wind', 'It is too windy to fly a kite.'),
  overcoat: g('大衣', 'a long coat for cold days', 'Put on your overcoat.'),
  sudden: g('突然的', 'happening very quickly', 'A sudden rain starts.'),
  gold: g('金子', 'a yellow metal', 'The ring is made of gold.'),
  outside: g('外面', 'not inside', 'The children play outside.'),
  camel: g('骆驼', 'a desert animal with a hump', 'A camel walks in the desert.'),
  chinese: g('中国的', 'from China', 'I like Chinese food.'),
  schoolbag: g('书包', 'a bag for school books', 'My schoolbag is heavy.'),
  invention: g('发明', 'a new thing someone makes', 'The light bulb is a great invention.'),
  cent: g('分', 'a small piece of money', 'This candy costs ten cents.'),
  purple: g('紫色的', 'a mix of red and blue', 'She wears a purple dress.'),
  useful: g('有用的', 'helping you do something', 'A map is useful on a trip.'),
  dish: g('盘子', 'a plate for food', 'Wash the dish after dinner.'),
  everywhere: g('到处', 'in all places', 'There are flowers everywhere.'),
  ninety: g('九十', 'the number 90', 'Grandma is ninety years old.'),
  composition: g('作文', 'a short piece of writing', 'I write a composition at home.'),
  crayon: g('蜡笔', 'a coloured stick for drawing', 'The child draws with a crayon.'),
  interest: g('兴趣', 'a feeling of wanting to know more', 'She has an interest in music.'),
  mine: g('我的', 'belonging to me', 'This pencil is mine.'),
  one: g('一', 'the number 1', 'I want one apple.'),
  arm: g('手臂', 'the part from your shoulder to your hand', 'He raises his arm.'),
  other: g('其他的', 'not this one', 'I like the other book.'),
  behaviour: g('行为', 'the way a person acts', 'Good behaviour helps the class.'),
  russian: g('俄国的', 'from Russia', 'He speaks a little Russian.'),
  his: g('他的', 'belonging to a boy or man', 'That is his bike.'),
  electric: g('电的', 'using electricity', 'We have an electric fan.'),
  not: g('不', 'used to say no', 'I am not tired.'),
  must: g('必须', 'have to', 'You must wear a seat belt.'),
  act: g('行动', 'to do something', 'We must act now.'),
  north: g('北方', 'the direction up on a map', 'Canada is north of the USA.'),
  book: g('书', 'pages you read', 'I read a book every night.'),
  used: g('用过的', 'not new', 'This is a used bike.'),
  news: g('新闻', 'new information', 'I watch the news with Dad.'),
  with: g('和', 'together', 'I go with my mum.'),
  february: g('二月', 'the second month', 'It often snows in February.'),
  rainy: g('下雨的', 'with a lot of rain', 'Take an umbrella on a rainy day.'),
  lion: g('狮子', 'a big wild cat', 'The lion lives in the zoo.'),
  pen: g('钢笔', 'a tool for writing with ink', 'I write with a blue pen.'),
  whose: g('谁的', 'belonging to which person', 'Whose bag is this?'),
  could: g('能够', 'was able to; might', 'Could you help me, please?'),
  him: g('他', 'a boy or man, not the subject', 'I see him in the park.'),
  sunny: g('晴朗的', 'with a lot of sun', 'It is a sunny morning.'),
  seventh: g('第七', 'number 7 in a list', 'Monday is the seventh.'),
  nose: g('鼻子', 'the part of the face for smelling', 'My nose is cold.'),
  ninth: g('第九', 'number 9 in a list', 'She finishes ninth in the race.'),
  bus: g('公共汽车', 'a big vehicle for many people', 'I take the bus to school.'),
  inch: g('英寸', 'a small unit of length', 'The insect is one inch long.'),
  postman: g('邮递员', 'a person who brings letters', 'The postman brings a letter.'),
  white: g('白色的', 'the colour of snow', 'The cat is white.'),
  over: g('在…上方', 'above', 'The lamp is over the table.'),
  everyday: g('每天的', 'used or done every day', 'This is my everyday bag.'),
  past: g('过去的', 'before now', 'In the past, we had no phones.'),
  knee: g('膝盖', 'the middle of your leg', 'I hurt my knee.'),
  ourselves: g('我们自己', 'we, as the object', 'We can do it ourselves.'),
  building: g('建筑物', 'a house, school, or shop', 'That building is very tall.'),
  swimming: g('游泳', 'moving in water', 'Swimming is good for you.'),
  my: g('我的', 'belonging to me', 'This is my desk.'),
  but: g('但是', 'used to show a different idea', 'I am small but strong.'),
  out: g('出去', 'away from inside', 'Please go out and play.'),
  november: g('十一月', 'the eleventh month', 'It is cold in November.'),
  japanese: g('日本的', 'from Japan', 'I like Japanese cartoons.'),
  ink: g('墨水', 'coloured liquid for pens', 'The pen has blue ink.'),
  instruction: g('说明', 'words that tell you what to do', 'Read the instruction first.'),
  or: g('或者', 'used to give a choice', 'Do you want tea or milk?'),
  thirty: g('三十', 'the number 30', 'There are thirty students.'),
  meeting: g('会议', 'people talking together about work', 'Dad has a meeting today.'),
  eighty: g('八十', 'the number 80', 'Grandpa is eighty years old.'),
  twelfth: g('第十二', 'number 12 in a list', 'December is the twelfth month.'),
  sir: g('先生', 'a polite word for a man', 'Thank you, sir.'),
  somewhere: g('某处', 'in a place, but not named', 'My keys are somewhere here.'),
  twentieth: g('第二十', 'number 20 in a list', 'Today is the twentieth.'),
  girl: g('女孩', 'a young female person', 'The girl reads a book.'),
  west: g('西方', 'the direction of sunset', 'The sun goes down in the west.'),
  shoulder: g('肩膀', 'the top of your arm', 'The bag is on my shoulder.'),
  discussion: g('讨论', 'talking about an idea', 'We have a discussion in class.'),
  car: g('汽车', 'a vehicle for a few people', 'Dad drives a car to work.'),
  pink: g('粉红色的', 'a light red colour', 'She likes a pink hat.'),
  ham: g('火腿', 'meat from a pig', 'I eat ham in my sandwich.'),
  comfortable: g('舒服的', 'nice to sit or wear', 'This chair is comfortable.'),
  father: g('爸爸', 'your male parent', 'My father helps me study.'),
  wealth: g('财富', 'a lot of money or things', 'Health is better than wealth.'),
  dog: g('狗', 'a pet that barks', 'The dog runs in the yard.'),
  ear: g('耳朵', 'the part of the body for hearing', 'She covers her ear.'),
  proper: g('适当的', 'right or correct', 'Wear proper shoes for PE.'),
  dumpling: g('饺子', 'a small food with filling', 'We eat dumplings at dinner.'),
  monday: g('星期一', 'the first day of the school week', 'Monday is after Sunday.'),
  season: g('季节', 'a part of the year, like summer', 'Spring is my favourite season.'),
  japan: g('日本', 'a country in Asia', 'Tokyo is in Japan.'),
  whenever: g('无论何时', 'at any time', 'Call me whenever you need help.'),
  fourteen: g('十四', 'the number 14', 'She is fourteen years old.'),
  robot: g('机器人', 'a machine that can work like a person', 'The robot can dance.'),
  dollar: g('美元', 'money used in the USA', 'This book costs one dollar.'),
  useless: g('无用的', 'not helpful', 'A broken pen is useless.'),
  there: g('那里', 'in that place', 'The shop is over there.'),
  yourselves: g('你们自己', 'you, as the object, for more than one', 'Please help yourselves.'),
  pleasant: g('愉快的', 'nice and friendly', 'We have a pleasant trip.'),
  eraser: g('橡皮', 'a thing that rubs out pencil marks', 'Lend me your eraser, please.'),
  raincoat: g('雨衣', 'a coat for rainy days', 'Wear a raincoat in the rain.'),
  sixth: g('第六', 'number 6 in a list', 'June is the sixth month.'),
  ice: g('冰', 'frozen water', 'The drink has ice in it.'),
  thirteen: g('十三', 'the number 13', 'There are thirteen chairs.'),
  madam: g('女士', 'a polite word for a woman', 'Can I help you, madam?'),
  boy: g('男孩', 'a young male person', 'The boy kicks the ball.'),
  pronunciation: g('发音', 'how you say a word', 'Her pronunciation is clear.'),
  twice: g('两次', 'two times', 'I brush my teeth twice a day.'),
  herself: g('她自己', 'she, as the object', 'She made the card herself.'),
  elder: g('年长的', 'older in a family', 'My elder sister is kind.'),
  flu: g('流感', 'a common illness like a bad cold', 'He stays home with the flu.'),
  east: g('东方', 'the direction of sunrise', 'The sun rises in the east.'),
  daily: g('每天的', 'happening every day', 'I take a daily walk.'),
  anywhere: g('任何地方', 'in any place', 'You can sit anywhere.'),
  granddaughter: g('孙女', 'the daughter of your child', 'Grandma loves her granddaughter.'),
  violin: g('小提琴', 'a musical instrument you play with a bow', 'She plays the violin.'),
  me: g('我', 'I, as the object', 'Can you help me?'),
  pencil: g('铅笔', 'a tool for writing and drawing', 'I write with a pencil.'),
  first: g('第一', 'before all others', 'I get up first in my family.'),
  them: g('他们', 'they, as the object', 'I see them at school.'),
  twelve: g('十二', 'the number 12', 'There are twelve months.'),
  zero: g('零', 'the number 0', 'The score is zero to one.'),
  ill: g('生病的', 'not well', 'She is ill today.'),
  twenty: g('二十', 'the number 20', 'I have twenty books.'),
  which: g('哪个', 'what one', 'Which colour do you like?'),
  in: g('在…里', 'inside', 'The cat is in the box.'),
  worker: g('工人', 'a person who does a job', 'The worker builds the house.'),
  these: g('这些', 'the ones here', 'These apples are sweet.'),
  christmas: g('圣诞节', 'a holiday in December', 'We give gifts at Christmas.'),
  mile: g('英里', 'a unit of long distance', 'The park is one mile away.'),
  canada: g('加拿大', 'a country north of the USA', 'Toronto is in Canada.'),
  off: g('离开', 'away from', 'Take your shoes off.'),
  thought: g('想法', 'an idea in your mind', 'I have a new thought.'),
  myself: g('我自己', 'I, as the object', 'I made it myself.'),
  april: g('四月', 'the fourth month', 'It rains a lot in April.'),
  down: g('向下', 'to a lower place', 'Please sit down.'),
  asian: g('亚洲的', 'from Asia', 'China is an Asian country.'),
  south: g('南方', 'the direction down on a map', 'Hainan is in the south.'),
  rapid: g('迅速的', 'very fast', 'The train is rapid.'),
  toothache: g('牙痛', 'pain in a tooth', 'I have a toothache.'),
  what: g('什么', 'used to ask for information', 'What is your name?'),
  head: g('头', 'the top part of the body', 'He nods his head.'),
  this: g('这个', 'the one here', 'This is my friend.'),
  monkey: g('猴子', 'an animal that can climb trees', 'The monkey eats a banana.'),
  green: g('绿色的', 'the colour of grass', 'The trees are green.'),
  saturday: g('星期六', 'the day after Friday', 'We play on Saturday.'),
  winner: g('获胜者', 'the person who wins', 'She is the winner of the race.'),
  oneself: g('自己', 'a person, as the object', 'One should be true to oneself.'),
  fourth: g('第四', 'number 4 in a list', 'April is the fourth month.'),
  their: g('他们的', 'belonging to them', 'Their house is near the school.'),
  danger: g('危险', 'a chance of getting hurt', 'Fire can be a danger.'),
  would: g('将要', 'used to talk about a wish or polite ask', 'Would you like some tea?'),
  neck: g('脖子', 'the part between head and body', 'A scarf is around her neck.'),
  sunday: g('星期日', 'the last day of the week', 'We rest on Sunday.'),
  bird: g('鸟', 'an animal with wings and feathers', 'A bird sings in the tree.'),
  golden: g('金色的', 'like gold in colour', 'She has golden hair.'),
  lab: g('实验室', 'a room for science work', 'We do tests in the lab.'),
  grandson: g('孙子', 'the son of your child', 'Grandpa plays with his grandson.'),
  up: g('向上', 'to a higher place', 'Please stand up.'),
  india: g('印度', 'a country in Asia', 'The Ganges is in India.'),
  nine: g('九', 'the number 9', 'I have nine crayons.'),
  word: g('单词', 'a unit of language', 'This word is new to me.'),
  foreigner: g('外国人', 'a person from another country', 'The foreigner asks for the way.'),
  socks: g('袜子', 'clothes for your feet', 'My socks are white.'),
  those: g('那些', 'the ones over there', 'Those birds are flying.'),
  success: g('成功', 'doing well at something', 'Hard work brings success.'),
  besides: g('此外', 'also; as well as', 'Besides English, I study French.'),
  all: g('全部', 'every one', 'All the students are here.'),
  seventy: g('七十', 'the number 70', 'The library has seventy chairs.'),
  every: g('每个', 'each one', 'Every child gets a gift.'),
  hen: g('母鸡', 'a female chicken', 'The hen lays an egg.'),
  themselves: g('他们自己', 'they, as the object', 'They cook dinner themselves.'),
  sleepy: g('困倦的', 'wanting to sleep', 'I feel sleepy at night.'),
  sixteen: g('十六', 'the number 16', 'She is sixteen years old.'),
  pancake: g('煎饼', 'a flat cake cooked in a pan', 'I eat a pancake for breakfast.'),
  hair: g('头发', 'what grows on your head', 'She has long hair.'),
  granny: g('奶奶', 'grandmother', 'Granny makes soup for me.'),
  may: g('可以', 'used to ask or show possibility', 'May I come in?'),
  everything: g('一切', 'all things', 'Everything is ready.'),
  ours: g('我们的', 'belonging to us', 'This classroom is ours.'),
  grammar: g('语法', 'rules for using a language', 'We learn English grammar.'),
  how: g('怎样', 'in what way', 'How do you go to school?'),
  and: g('和', 'used to join words', 'I like apples and bananas.'),
  bye: g('再见', 'a word when you leave', 'Bye! See you tomorrow.'),
  black: g('黑色的', 'the colour of night', 'The cat is black.'),
  our: g('我们的', 'belonging to us', 'Our teacher is kind.'),
  fifteen: g('十五', 'the number 15', 'I have fifteen pencils.'),
  chocolate: g('巧克力', 'a sweet brown food', 'I eat a piece of chocolate.'),
  mouth: g('嘴', 'the part of the face for eating and talking', 'Open your mouth, please.'),
  money: g('钱', 'coins and notes you use to buy things', 'I save money in a box.'),
  helpful: g('有帮助的', 'giving help', 'The map is very helpful.'),
  european: g('欧洲的', 'from Europe', 'Paris is a European city.'),
  yellow: g('黄色的', 'the colour of a lemon', 'The banana is yellow.'),
  condition: g('状况', 'how something is', 'The bike is in good condition.'),
  fish: g('鱼', 'an animal that lives in water', 'The fish swims in the river.'),
  why: g('为什么', 'for what reason', 'Why are you late?'),
  no: g('不', 'the opposite of yes', 'No, I am not hungry.'),
  fifty: g('五十', 'the number 50', 'The book has fifty pages.'),
  to: g('到', 'towards a place or person', 'We walk to school.'),
  seven: g('七', 'the number 7', 'There are seven days in a week.'),
  fridge: g('冰箱', 'a cold box for food', 'Milk is in the fridge.'),
  hand: g('手', 'the end of your arm', 'Raise your hand, please.'),
  itself: g('它自己', 'it, as the object', 'The cat washes itself.'),
  everybody: g('每个人', 'every person', 'Everybody is here.'),
  brown: g('棕色的', 'the colour of chocolate', 'The dog is brown.'),
  september: g('九月', 'the ninth month', 'School starts in September.'),
  finger: g('手指', 'one of the five parts of a hand', 'I cut my finger.'),
  thank: g('感谢', 'to say you are glad for help', 'I thank my teacher.'),
  on: g('在…上', 'touching the top of something', 'The book is on the table.'),
  hers: g('她的', 'belonging to her', 'The red bag is hers.'),
  chairman: g('主席', 'the leader of a meeting', 'The chairman opens the meeting.'),
  of: g('…的', 'belonging to; about', 'The colour of the sky is blue.'),
  about: g('关于', 'on the subject of', 'This book is about animals.'),
  december: g('十二月', 'the twelfth month', 'Christmas is in December.'),
  ok: g('好的', 'yes; all right', 'OK, I will help you.'),
  cooker: g('炉具', 'a machine for cooking', 'Mum uses the cooker.'),
  people: g('人们', 'men, women and children', 'Many people wait for the bus.'),
  china: g('中国', 'a country in Asia', 'I live in China.'),
  it: g('它', 'a thing or animal', 'It is a nice day.'),
  handbag: g('手提包', 'a small bag a woman carries', 'Mum puts keys in her handbag.'),
  plane: g('飞机', 'a machine that flies in the sky', 'The plane flies above the clouds.'),
  three: g('三', 'the number 3', 'I have three cats.'),
  greeting: g('问候', 'hello words', 'A smile is a kind greeting.'),
  whatever: g('无论什么', 'anything at all', 'Take whatever you need.'),
  january: g('一月', 'the first month', 'January is cold here.'),
  orange: g('橙色的', 'the colour of an orange fruit', 'I like orange juice.'),
  october: g('十月', 'the tenth month', 'National Day is in October.'),
  ruler: g('尺子', 'a straight tool for measuring', 'Draw a line with a ruler.'),
  grandchild: g('孙子', 'the child of your child', 'She visits her grandchild.'),
  excite: g('使兴奋', 'to make someone feel happy and full of energy', 'The news will excite the class.'),
  cd: g('光盘', 'a disc for music or files', 'I listen to a CD.'),
  us: g('我们', 'we, as the object', 'Come with us.'),
  grape: g('葡萄', 'a small round fruit', 'I wash the grapes.'),
  indian: g('印度的', 'from India', 'They eat Indian food.'),
  into: g('进入', 'to the inside of', 'She walks into the room.'),
  while: g('当…时', 'during the time that', 'I read while I wait.'),
  american: g('美国人', 'a person from the USA', 'My pen pal is American.'),
  that: g('那个', 'the one over there', 'That is my school.'),
  advertisement: g('广告', 'words or pictures that sell something', 'I saw an advertisement on TV.'),
  somebody: g('某人', 'a person, but not named', 'Somebody is at the door.'),
  tower: g('塔', 'a tall building', 'We climb the tower.'),
  hat: g('帽子', 'clothes you wear on your head', 'He puts on a hat.'),
  who: g('谁', 'what person', 'Who is your teacher?'),
  fifth: g('第五', 'number 5 in a list', 'May is the fifth month.'),
  manager: g('经理', 'a person who leads a shop or team', 'The manager is in the office.'),
  leg: g('腿', 'the part of the body you walk with', 'The chair has four legs.'),
  yourself: g('你自己', 'you, as the object', 'Please do it yourself.'),
  himself: g('他自己', 'he, as the object', 'He made the cake himself.'),
  two: g('二', 'the number 2', 'I have two hands.'),
  third: g('第三', 'number 3 in a list', 'March is the third month.'),
  six: g('六', 'the number 6', 'A cube has six sides.'),
  recorder: g('录音机', 'a machine that records sound', 'Play the recorder, please.'),
  eighteen: g('十八', 'the number 18', 'She is eighteen years old.'),
  cloudy: g('多云的', 'with many clouds', 'It is a cloudy afternoon.'),
  sentence: g('句子', 'a group of words with a full idea', 'Write a sentence about your pet.'),
  trousers: g('裤子', 'clothes for the legs', 'These trousers are too long.'),
  anyway: g('无论如何', 'in any case', 'Anyway, we can try again.'),
  red: g('红色的', 'the colour of blood or a rose', 'The apple is red.'),
  kilometer: g('千米', 'a unit of long distance', 'The school is two kilometers away.'),
  asia: g('亚洲', 'a large part of the world', 'China is in Asia.'),
  gym: g('健身房', 'a place to do sports', 'We run in the gym.'),
  your: g('你的', 'belonging to you', 'Is this your pen?'),
  eleven: g('十一', 'the number 11', 'The shop opens at eleven.'),
  cruel: g('残忍的', 'not kind; hurting others', 'Do not be cruel to animals.'),
  yes: g('是的', 'used to agree', 'Yes, I can help you.'),
  australia: g('澳大利亚', 'a country and island', 'Kangaroos live in Australia.'),
  training: g('训练', 'practice to get better', 'The team has training today.'),
  sixty: g('六十', 'the number 60', 'There are sixty minutes in an hour.'),
  game: g('游戏', 'something you play for fun', 'Let us play a game.'),
  thursday: g('星期四', 'the day after Wednesday', 'We have art on Thursday.'),
  farmer: g('农民', 'a person who grows food', 'The farmer feeds the hens.'),
  chest: g('胸部', 'the front of the body', 'He puts his hand on his chest.'),
  eye: g('眼睛', 'the part of the body for seeing', 'She has bright eyes.'),
  speaker: g('演讲者', 'a person who talks to a group', 'The speaker is very clear.'),
  piano: g('钢琴', 'a large musical instrument with keys', 'She plays the piano.'),
  australian: g('澳大利亚的', 'from Australia', 'He has an Australian friend.'),
  tenth: g('第十', 'number 10 in a list', 'October is the tenth month.'),
  when: g('何时', 'at what time', 'When do you get up?'),
  sister: g('姐妹', 'a girl with the same parents', 'My sister is in Grade 5.'),
  london: g('伦敦', 'the capital of England', 'Big Ben is in London.'),
  for: g('为了', 'used to show purpose', 'This gift is for you.'),
  fine: g('好的', 'well; all right', 'I am fine, thank you.'),
  pollution: g('污染', 'dirty air, water, or land', 'Cars can cause pollution.'),
  mystery: g('谜', 'something hard to understand', 'The story is a mystery.'),
  anybody: g('任何人', 'any person', 'Is anybody at home?'),
  outgoing: g('外向的', 'liking to meet people', 'She is an outgoing girl.'),
  alright: g('好吧', 'OK; all right', 'Alright, let us start.'),
  loving: g('充满爱的', 'showing love', 'She has a loving family.'),
  unhappy: g('不高兴的', 'not happy', 'He looks unhappy today.'),
  southeast: g('东南', 'between south and east', 'Guangzhou is in the southeast.'),
  conjunction: g('连词', 'a word that joins words, like and', 'And is a conjunction.'),
  have: g('有', 'to own or hold', 'I have a new book.'),
  upon: g('在…上', 'on', 'Once upon a time, there was a king.'),
  wake: g('醒来', 'to stop sleeping', 'I wake up at seven.'),
  girlfriend: g('女朋友', 'a girl you like as a partner', 'He walks with his girlfriend.'),
  spoken: g('口头的', 'said with the voice, not written', 'We practice spoken English.'),
  unimportant: g('不重要的', 'not important', 'That mistake is unimportant.'),
  africa: g('非洲', 'a large part of the world', 'Egypt is in Africa.'),
  entertainment: g('娱乐', 'films, games, and fun', 'TV is a kind of entertainment.'),
  found: g('创立', 'to start a school or group', 'They found a new club.'),
  latest: g('最新的', 'the most recent', 'This is the latest news.'),
  jew: g('犹太人', 'a person of the Jewish people', 'He is a Jew from New York.'),
  anymore: g('不再', 'no longer', 'I do not live there anymore.'),
  unable: g('不能的', 'not able', 'I am unable to come today.'),
  pro: g('职业选手', 'a person who does a job as work, not a hobby', 'She is a tennis pro.'),
  impossible: g('不可能的', 'not able to happen', 'It is impossible to fly like a bird.'),
  furry: g('毛茸茸的', 'covered with soft hair', 'The kitten is furry.'),
  most: g('最', 'more than all others', 'This is the most interesting book.'),
  teen: g('青少年', 'a person from 13 to 19', 'My cousin is a teen.'),
  specifically: g('具体地', 'in a clear and exact way', 'She asked specifically for tea.'),
  hey: g('嘿', 'a word to call someone', 'Hey, wait for me!'),
  dad: g('爸爸', 'father', 'Dad picks me up after school.'),
  sixteenth: g('第十六', 'number 16 in a list', 'Today is the sixteenth.'),
  casually: g('随意地', 'in a relaxed way', 'He talks casually with friends.'),
  spotlight: g('聚光灯', 'a strong light on a stage', 'The singer stands in the spotlight.'),
  later: g('后来', 'after some time', 'See you later.'),
  lookout: g('瞭望', 'watching for danger', 'Keep a lookout for cars.'),
  possibly: g('可能', 'maybe', 'It will possibly rain.'),
  misleading: g('误导的', 'making people think the wrong thing', 'The sign is misleading.'),
  adverb: g('副词', 'a word like quickly or very', 'Slowly is an adverb.'),
  thirteenth: g('第十三', 'number 13 in a list', 'Friday the thirteenth is a date.'),
  cookie: g('饼干', 'a small sweet cake', 'I eat a cookie after lunch.'),
  cream: g('奶油', 'the thick part of milk', 'I put cream in my coffee.'),
  embarrassed: g('尴尬的', 'feeling shy or silly', 'He feels embarrassed in class.'),
  cigarette: g('香烟', 'a roll of tobacco people smoke', 'Cigarettes are bad for you.'),
  instance: g('例子', 'an example', 'For instance, cats like fish.'),
  stair: g('楼梯', 'a step you walk on', 'Be careful on the stair.'),
  outdoor: g('户外的', 'outside a building', 'We like outdoor games.'),
  writer: g('作家', 'a person who writes books', 'The writer visits our school.'),
  theatre: g('剧院', 'a place to watch a play', 'We go to the theatre tonight.'),
  brazilian: g('巴西的', 'from Brazil', 'He is a Brazilian football fan.'),
  labor: g('劳动', 'hard work with the body', 'Farm labor is hard.'),
  association: g('协会', 'a group of people with the same goal', 'She joins a sports association.'),
  many: g('许多', 'a large number', 'Many students like music.'),
  transportation: g('交通', 'ways of moving people or things', 'Buses are public transportation.'),
  russia: g('俄罗斯', 'a large country in Europe and Asia', 'Moscow is in Russia.'),
  lost: g('丢失的', 'you cannot find it', 'I look for my lost key.'),
  calculator: g('计算器', 'a small machine for maths', 'Use a calculator for this sum.'),
  from: g('从', 'starting at a place or time', 'I am from Beijing.'),
  much: g('许多', 'a large amount', 'Thank you very much.'),
  mouse: g('老鼠', 'a small animal with a long tail', 'A mouse runs under the table.'),
  terrorist: g('恐怖分子', 'a person who hurts people to scare others', 'The news talks about a terrorist.'),
  attendant: g('服务员', 'a person who helps customers', 'The attendant shows us our seats.'),
  'x-ray': g('X光', 'a special photo of bones', 'The doctor takes an x-ray.'),
  bicycle: g('自行车', 'a bike you ride', 'I go to school by bicycle.'),
  july: g('七月', 'the seventh month', 'Summer holiday starts in July.'),
  lighting: g('照明', 'lights in a room or street', 'The lighting in the room is soft.'),
  french: g('法语', 'the language of France', 'She learns French at school.'),
  vocabulary: g('词汇', 'the words you know', 'I learn new vocabulary every day.'),
  unfriendly: g('不友好的', 'not kind to others', 'The dog looks unfriendly.'),
  fourteenth: g('第十四', 'number 14 in a list', 'Today is the fourteenth.'),
  photo: g('照片', 'a picture from a camera', 'This photo is of my family.'),
  thirtieth: g('第三十', 'number 30 in a list', 'June has a thirtieth day.'),
  seventeenth: g('第十七', 'number 17 in a list', 'He was born on the seventeenth.'),
  bored: g('无聊的', 'not interested', 'I feel bored on a rainy day.'),
  silver: g('银', 'a grey-white metal', 'The ring is silver.'),
  singer: g('歌手', 'a person who sings', 'The singer is on TV.'),
  restroom: g('洗手间', 'a toilet in a public place', 'Where is the restroom?'),
  more: g('更多', 'a larger amount', 'I need more paper.'),
  honor: g('尊敬', 'to show respect', 'We honor our teachers.'),
  unhealthy: g('不健康的', 'not good for the body', 'Too much candy is unhealthy.'),
  insect: g('昆虫', 'a small animal like an ant or bee', 'An insect sits on the leaf.'),
  shall: g('将要', 'used to offer or talk about the future', 'Shall we go now?'),
  nearby: g('附近的', 'not far away', 'There is a shop nearby.'),
  pronoun: g('代词', 'a word like he, she, or it', 'He is a pronoun.'),
  saying: g('谚语', 'a short common sentence', 'This old saying is true.'),
  france: g('法国', 'a country in Europe', 'Paris is in France.'),
  nineteenth: g('第十九', 'number 19 in a list', 'Today is the nineteenth.'),
  turkey: g('火鸡', 'a large bird people eat', 'We eat turkey at the party.'),
  tasty: g('美味的', 'good to eat', 'The soup is tasty.'),
  are: g('是', 'a form of be for we, you, they', 'They are my friends.'),
  disabled: g('残疾的', 'not able to use a part of the body well', 'The school helps disabled students.'),
  mom: g('妈妈', 'mother', 'Mom reads me a story.'),
  jazz: g('爵士乐', 'a kind of music', 'Dad likes jazz.'),
  worst: g('最差的', 'the most bad', 'This is the worst day.'),
  clothing: g('服装', 'clothes', 'Warm clothing is needed in winter.'),
  color: g('颜色', 'red, blue, green, and others', 'What color is your bag?'),
  mars: g('火星', 'a red planet', 'People want to visit Mars.'),
  penny: g('便士', 'a small British coin', 'I find a penny on the floor.'),
  fax: g('传真', 'a copy sent by phone line', 'Please send a fax to the office.'),
  phone: g('电话', 'a tool for talking to people far away', 'I call Mum on the phone.'),
  porridge: g('粥', 'soft food made from grain and water', 'I eat porridge in the morning.'),
  autograph: g('签名', 'a famous person\'s name written by them', 'She asks the singer for an autograph.'),
  eleventh: g('第十一', 'number 11 in a list', 'November is the eleventh month.'),
  talent: g('才能', 'a natural skill', 'She has a talent for music.'),
  phrase: g('短语', 'a small group of words', 'Learn this useful phrase.'),
  yoghurt: g('酸奶', 'thick sour milk food', 'I eat yoghurt with fruit.'),
  shine: g('照耀', 'to give out light', 'The stars shine at night.'),
  an: g('一个', 'a, used before a, e, i, o, u', 'I eat an apple.'),
  homeland: g('祖国', 'the country you come from', 'He loves his homeland.'),
  maths: g('数学', 'the study of numbers', 'Maths is my favourite subject.'),
  foot: g('脚', 'the part of the body you stand on', 'My left foot hurts.'),
  escalator: g('自动扶梯', 'moving stairs', 'We take the escalator in the mall.'),
  do: g('做', 'to perform an action', 'Please do your homework.'),
  humorous: g('幽默的', 'funny in a smart way', 'The story is humorous.'),
  easily: g('容易地', 'with little trouble', 'She can swim easily.'),
  verb: g('动词', 'a word for an action, like run', 'Go is a verb.'),
  is: g('是', 'a form of be for he, she, it', 'She is my sister.'),
  announce: g('宣布', 'to tell people news', 'The teacher will announce the winner.'),
  hello: g('你好', 'a word when you meet someone', 'Hello, my name is Li Hua.'),
  meter: g('米', 'a unit of length', 'The table is two meters long.'),
  infinitive: g('不定式', 'the to + verb form, like to go', 'To run is an infinitive.'),
  prediction: g('预测', 'a guess about the future', 'My prediction is rain tomorrow.'),
  tense: g('时态', 'a verb form that shows time', 'Past tense talks about yesterday.'),
  homeless: g('无家可归的', 'with no home', 'They help homeless people.'),
  paris: g('巴黎', 'the capital of France', 'The Eiffel Tower is in Paris.'),
  elbow: g('肘', 'the middle of your arm', 'I rest my elbow on the desk.'),
  injure: g('伤害', 'to hurt a person or animal', 'Do not injure the bird.'),
  zigzag: g('之字形', 'a line that goes left and right', 'The path is a zigzag.'),
  singular: g('单数的', 'for one person or thing', 'Cat is a singular noun.'),
  eighteenth: g('第十八', 'number 18 in a list', 'Today is the eighteenth.'),
  slipper: g('拖鞋', 'soft shoes for home', 'I wear a slipper in the house.'),
  fifteenth: g('第十五', 'number 15 in a list', 'Today is the fifteenth.'),
  unusual: g('不寻常的', 'not common', 'That is an unusual flower.'),
  cola: g('可乐', 'a sweet brown drink', 'I order a cola.'),
  teach: g('教', 'to help someone learn', 'They teach us English.'),
  specially: g('专门地', 'for one special reason', 'This gift is specially for you.'),
  shampoo: g('洗发水', 'soap for washing hair', 'Wash your hair with shampoo.'),
  etiquette: g('礼节', 'polite rules', 'Table etiquette is important.'),
  queue: g('排队', 'a line of people waiting', 'Please queue for the bus.'),
  impolite: g('不礼貌的', 'not polite', 'It is impolite to shout.'),
  realistic: g('现实的', 'like real life', 'The picture looks realistic.'),
  towards: g('朝向', 'in the direction of', 'He walks towards the school.'),
  disappointing: g('令人失望的', 'making you feel sad because it is not good', 'The rainy picnic is disappointing.'),
  player: g('选手', 'a person in a game', 'She is a basketball player.'),
  will: g('将要', 'used to talk about the future', 'I will call you tonight.'),
  really: g('真正地', 'in fact; very', 'I really like this song.'),
  website: g('网站', 'pages on the internet', 'I open the school website.'),
  prove: g('证明', 'to show that something is true', 'These facts prove he is right.'),
  standard: g('标准', 'a normal level of quality', 'This is the standard size.'),
  engineer: g('工程师', 'a person who designs machines', 'My uncle is an engineer.'),
  keyboard: g('键盘', 'keys you press on a piano or computer', 'Type the word on the keyboard.'),
  college: g('大学', 'a school after high school', 'She will go to college.'),
  strict: g('严格的', 'making people follow rules closely', 'Our teacher is strict but kind.'),
  clap: g('鼓掌', 'to hit your hands together', 'Please clap for the singer.'),
  pride: g('自豪', 'a happy feeling about something you did', 'She looks at her work with pride.'),
  license: g('执照', 'a paper that lets you do something', 'Dad has a driving license.'),
  university: g('大学', 'a school for higher study', 'He studies at the university.'),
  litter: g('垃圾', 'paper and waste on the ground', 'Do not throw litter on the street.'),
  whether: g('是否', 'if something is true or not', 'I do not know whether it will rain.'),
  shame: g('羞愧', 'a sad feeling after doing wrong', 'He feels shame after the lie.'),
  heaven: g('天堂', 'a very happy place', 'The garden looks like heaven.'),
  rubber: g('橡皮', 'a thing that rubs out pencil marks', 'Lend me your rubber, please.'),
  background: g('背景', 'what happened before; the back of a picture', 'Tell me your family background.'),
  passport: g('护照', 'a book that lets you enter another country', 'Show your passport at the airport.'),
  offend: g('冒犯', 'to hurt someone with words', 'Do not offend your friend.'),
  tragedy: g('悲剧', 'a very sad event', 'The story ends in a tragedy.'),
  chew: g('咀嚼', 'to break food with your teeth', 'Please chew your food slowly.'),
  agent: g('代理人', 'a person who helps you with business', 'A travel agent books the tickets.'),
  elevator: g('电梯', 'a box that takes you up and down in a building', 'We take the elevator to floor 5.'),
  furniture: g('家具', 'tables, chairs and beds', 'The room has new furniture.'),
  fold: g('折叠', 'to bend paper or cloth', 'Fold the paper in half.'),
  hallway: g('走廊', 'a long path inside a building', 'Walk quietly in the hallway.'),
  recipe: g('食谱', 'steps for cooking a dish', 'Mum follows a cake recipe.'),
  dormitory: g('宿舍', 'a building where students sleep', 'He lives in the school dormitory.'),
  percent: g('百分之', 'a part of one hundred', 'Ten percent of the class are late.'),
  teenager: g('青少年', 'a person from 13 to 19', 'My cousin is a teenager.'),
  direct: g('直接的', 'straight, with no stop', 'This is a direct train to Beijing.'),
  film: g('电影', 'a movie', 'We watch a film at home.'),
  neither: g('也不', 'not one and not the other', 'Neither answer is right.'),
  wonder: g('想知道', 'to want to know', 'I wonder where my cat is.'),
  represent: g('代表', 'to speak or act for others', 'She will represent our class.'),
  microwave: g('微波炉', 'a machine that heats food quickly', 'Heat the soup in the microwave.'),
  impress: g('留下印象', 'to make someone think well of you', 'His drawing will impress the teacher.'),
  unpleasant: g('不愉快的', 'not nice', 'The smell is unpleasant.'),
  risk: g('风险', 'a chance that something bad happens', 'Do not take a risk on the ice.'),
  beyond: g('在…之外', 'on the far side of', 'The hills are beyond the river.'),
  slide: g('滑', 'to move smoothly', 'The kids slide on the ice.')
}
